name: Build-and-Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: dotnet-install
      run: |
        sudo apt install curl wget -y
        wget https://packages.microsoft.com/config/debian/13/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update && \ sudo apt-get install -y dotnet-sdk-8.0

        sudo apt-get install -y dotnet-runtime-8.0
      
    
    - name: Build Windows Binary
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
    
    - name: Build Linux Binary
      run: dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true
    
    - name: Create Debian Package
      run: |
        mkdir -p deb_package/DEBIAN
        mkdir -p deb_package/usr/local/bin
        cp bin/Release/net6.0/linux-x64/publish/Passgen_cli deb_package/usr/local/bin/
        echo "Package: passgen-cli" > deb_package/DEBIAN/control
        echo "Version: 1.0" >> deb_package/DEBIAN/control
        echo "Architecture: amd64" >> deb_package/DEBIAN/control
        echo "Maintainer: Your Name <Nevio>" >> deb_package/DEBIAN/control
        echo "Description: Password Generator CLI" >> deb_package/DEBIAN/control
        dpkg-deb --build deb_package
    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/Release/net6.0/win-x64/publish/Passgen_cli.exe
        asset_name: Passgen_cli_windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/Release/net6.0/linux-x64/publish/Passgen_cli
        asset_name: Passgen_cli_linux
        asset_content_type: application/octet-stream
    
    - name: Upload Debian Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./deb_package.deb
        asset_name: passgen-cli.deb
        asset_content_type: application/vnd.debian.binary-package
