name: Build-and-Releases :3

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install curl wget

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

##################################################################33

    - name: Build Linux
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/linux
      shell: bash

    - name: Build Windows
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/windows
      shell: bash


      #######################################################################

    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev build-essential
        sudo gem install --no-document fpm
      shell: bash

    #########################################################################
    
    - name: Create Debian package
      run: |
        VERSION=${{ github.event.release.tag_name }}
        fpm -s dir -t deb -n passgen_cli -v $VERSION \
          --prefix /usr/local/bin ./publish/linux/
      shell: bash


    - name: List directory contents
      run: |
        echo "Linux build:"
        ls -R ./publish/linux
        echo "Windows build:"
        ls -R ./publish/windows
        echo "Current directory:"
        ls

    - name: List files to upload
      run: |
        ls -l ./publish/linux/passgen_cli
        ls -l ./publish/windows/passgen_cli.exe
        ls -l ./passgen_cli_${{ steps.get_version.outputs.VERSION }}_amd64.deb


    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}


    
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/linux/passgen_cli
        asset_name: passgen_cli_linux
        asset_content_type: application/octet-stream
    
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/windows/passgen_cli.exe
        asset_name: passgen_cli_windows.exe
        asset_content_type: application/octet-stream
    
    - name: Upload Debian Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./passgen_cli_${{ github.ref_name }}_amd64.deb
        asset_name: passgen_cli_${{ github.ref_name }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package
    
    


