name: Build-and-Releases :3 (gtp)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Linux
      run: |
        dotnet publish Passgen.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/linux

    - name: Build Windows
      run: |
        dotnet publish Passgen.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/windows

    - name: Debug Build
      run: |
        echo "Linux build output:"
        ls -R ./publish/linux
        echo "Windows build output:"
        ls -R ./publish/windows
        dotnet --info

    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev build-essential
        sudo gem install --no-document fpm

    - name: Create Debian package
      run: |
        # Entferne das führende 'v' aus dem GitHub Release Tag
        VERSION="${{ github.event.release.tag_name }}"
        VERSION="${VERSION#v}"  # entfernt führendes 'v'

        echo "Building Debian package for version $VERSION"

        # Erstelle das Debian Paket mit passgen als Name
        fpm -s dir -t deb -n passgen -v $VERSION \
          --prefix /usr/local/bin ./publish/linux/Passgen

        # Finde die erzeugte .deb Datei
        DEB_FILE=$(ls passgen_*_amd64.deb)
        echo "deb_file=$DEB_FILE" >> $GITHUB_ENV




    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/linux/Passgen
        asset_name: Passgen_linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/windows/Passgen.exe
        asset_name: Passgen_windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Debian Package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ env.deb_file }}
        asset_name: ${{ env.deb_file }}
        asset_content_type: application/vnd.debian.binary-package

