name: Build-and-Releases :3

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install curl wget

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

##################################################################33

    - name: Build Linux
      run: |
        dotnet publish YourProjectName.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/linux

    - name: Build Windows
      run: |
        dotnet publish YourProjectName.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/windows


    - name: Debug Build Process
      run: |
        echo "Current directory structure:"
        ls -R
        echo "dotnet --info:"
        dotnet --info


      #######################################################################

    - name: Install fpm
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev build-essential
        sudo gem install --no-document fpm
      shell: bash

    #########################################################################
    
    - name: Create Debian package
      run: |
        VERSION=${{ github.event.release.tag_name }}
        fpm -s dir -t deb -n passgen_cli -v $VERSION \
          --prefix /usr/local/bin ./publish/linux/
      shell: bash


    - name: List directory contents
      run: |
        echo "Linux build:"
        ls -R ./publish/linux
        echo "Windows build:"
        ls -R ./publish/windows
        echo "Current directory:"
        ls

    - name: List build outputs
      run: |
        echo "Linux build output:"
        ls -R ./publish/linux/
        echo "Windows build output:"
        ls -R ./publish/windows/




    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}



    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/linux/YourExecutableName
        asset_name: YourExecutableName_linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./publish/windows/YourExecutableName.exe
        asset_name: YourExecutableName_windows.exe
        asset_content_type: application/octet-stream





